### PR TITLE
Add function to validate personal identity number according to select…

### PR DESCRIPTION
**Pull request by joelmandell**
…ed format (ValidFormat).

**Type of change**

- [x] New feature
- [ ] Bug fix
- [ ] Security patch
- [ ] Documentation update

**Description**

Adds an function to validate format to what is expected i.e. personal identity number provided to function should be according to a specific format.

**Related issue**

**Motivation**

I could have done this by myself. But it feels strange to pull up and do some manual regex or string-matching just for checking format of personal identity number. Why should I then use a nuget-package in first place? If I need to add some logic anyway  (Okay not such a  big deal, probably a oneliner as an extension method, but anyways 😂). 
And maybe someone else could benefit from this function?

**Checklist**

- [ ] I have read the **CONTRIBUTING** document. (Could not find in repo)
- [ ] I have read and accepted the **Code of conduct**  (Could not find in repo)
- [x] Tests passes.
- [ ] Style lints passes. (dunno)
- [x] Documentation of new public methods exists.

- [x] New tests added which covers the added code. (The dataset is added inline, because it seemed tedious atm to add to meta)
- [x] Documentation is updated.

### CODE REVIEW

**Comment by Johannestegner** [comment]
Thank you for the pull request!

The personnummer tool is intended to accept the most common formats and then format them to the format that you need it to be for the specific use case. Further validation, especially formats, is currently outside the scope of the project.

As you said, an extension method might be a good idea, or you could always just pull the code you need straight from the repository into your project and adapt is as you wish (its MIT after all)! :)

**Comment by joelmandell** [comment]
As the function only uses internal functions and is not extending, could you reconsider the closing of this issue? It would be easier to pull a nuget-package for different projects than having an extension method added for different projects?

**Comment by frozzare** [comment]
We have talked in the personnummer team about this issue and will not reopen it as we don't think the functionally is needed in our packages.

We have 19 packages to maintain and this functionality will not bring that big of value and have to think about the big picture  cannot just add functionality that one person needs. We have a specification to follow for all packages, so we cannot just merge stuff in to one package and let it be, in order to something to make it into our packages is has to be a discussion in the [meta](https://github.com/personnummer/meta) repository first.

The best solution for you is to fork this project and add the functionality you want and use your fork in your project as @Johannestegner pointed out.

**Comment by joelmandell** [comment]
Got it. Thx @frozzare

**Pull request closed without merging**
